services:
  - type: web
    name: funil-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "frontend/dist"

  - type: web
    name: funil-backend
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
