services:
  - type: web
    name: funil-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "frontend/dist"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: funil-backend
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    autoDeploy: true
