services:
  - type: static_site
    name: funil-frontend
    root: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist"

  - type: web
    name: funil-backend
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true
